theme: minima
title: Hung Pham's Homepage
email: hungpham2511@gmail.com
author: Hung Pham
github_username: hungpham2511
description: My research page

markdown: kramdown
permalink: pretty

sass:
    sass_dir: _sass